version: '3.8'
services:
  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - ./server/.env
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data_container:/data/db

  server: 
    build: ./server
    container_name: server
    ports:
      - 3000:3000

  client: 
    build: ./client
    container_name: client
    ports:
      - 3001:3001

# volumes:
#   mongodb_data_container: