version: '3.8'
services:
  mongodb:
    container_name: mongodb
    restart: unless-stopped
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017

  server: 
    build: ./server
    container_name: server
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  client: 
    build: ./client
    container_name: client
    ports:
      - 3001:3001
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL=${API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_FE=${NEXT_PUBLIC_FE}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_AUTH_ISSUER=${NEXT_PUBLIC_AUTH_ISSUER}
      - KEYCLOAK_ID=${KEYCLOAK_ID}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}
      - KEYCLOAK_AUTHORIZATION=${KEYCLOAK_AUTHORIZATION}
    depends_on:
      - server
      - keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: 'start-dev'
    depends_on:
      - server