version: '3.8'
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ushira
      - MONGO_INITDB_ROOT_PASSWORD=ushira
    ports:
      - 27017:27017

  server: 
    build: ./server
    container_name: server
    ports:
      - 3000:3000

  client: 
    build: ./client
    container_name: client
    ports:
      - 3001:3001